CREATE DATABASE celke

CREATE TABLE faq (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tema VARCHAR(50) NOT NULL,
  pergunta VARCHAR(255) NOT NULL,
  resposta VARCHAR(255) NOT NULL,
)
